//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.CourseCentres = new HashSet<CourseCentre>();
            this.RegisteredCourses = new HashSet<RegisteredCours>();
        }
    
        public int CourseId { get; set; }
        public string CourseDesc { get; set; }
        public int SubjectId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> Usertype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCentre> CourseCentres { get; set; }
        public virtual Session Session { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisteredCours> RegisteredCourses { get; set; }
    }
}
