//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Booking
    {
        public int Id { get; set; }
        public int roomId { get; set; }
        public int userId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool isCheckedIn { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
