//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypeAmenity
    {
        public int id { get; set; }
        public int amenityId { get; set; }
        public int roomTypeId { get; set; }
    
        public virtual Amenity Amenity { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
